### ISSUE TITLE
Contributor Permissions

### ISSUE THREAD

**Issue by casato** [SentimentAnalysisInSE/stackoverflow_analysis#1]
I don't seem to have the appropriate permissions to add to this repo. 

Output when trying to push:
~~~~
remote: Permission to SentimentAnalysisInSE/stackoverflow_analysis.git denied to casato.
fatal: unable to access 'https://github.com/SentimentAnalysisInSE/stackoverflow_analysis.git/': The requested URL returned error: 403
~~~~

Thanks

**Comment by bcdasilv** [comment]
Sorry, Clay. I had invited you to the organization I created but not to the internal repo. Now it's fixed. Thanks!
