### ISSUE TITLE
Map reputation across all users in data set

### ISSUE THREAD

**Issue by casato** [SentimentAnalysisInSE/stackoverflow_analysis#12]
Make SQL query(s) to get the reputation of all users and separate them into categories of
Zero or below, First, Second, Third, and Fourth Quartiles.

**Comment by bcdasilv** [comment]
Well... when we discussed this issue last meeting I wasn't considering negative reputations. I had not realized that it's possible. I don't know how the distribution of negative reputation is. If it's well spread (high variance) we can try to provide categories over the negative spectrum. For now, I think that's fine if we put together zero and below in the same bucket.

**Comment by casato** [comment]
After running some queries on the database it looked like my assumption was wrong anyway.

After looking it up from [StackExchange](https://stackoverflow.com/help/whats-reputation): "All users start with one reputation point, and reputation can never drop below 1." 

So the new groups would be 
- One
- First Quartile
- Second Quartile
- Third Quartile
- Fourth Quartile

**Comment by bcdasilv** [comment]
All right! And well.. this makes our lives easier.

**Comment by casato** [comment]
Reputations:
First Quartile: 2-8
Second Quartile: 9-21
Third Quartile: 22-83
Fourth Quartile: 84+

Highest Reputation: 1,070,456

Total users: 9,737,246
Number of ones: 6,684,121
Total with 2 or higher: 3,053,125

**Comment by bcdasilv** [comment]
Nice! Can't wait to see the distribution plotted. Can you do that?
