### ISSUE TITLE
Clean up post bodies

### ISSUE THREAD

**Issue by casato** [SentimentAnalysisInSE/stackoverflow_analysis#5]
Remove links, html tags, source code from post bodies.

**Comment by bcdasilv** [comment]
You can also try to use the API to strip the HTML tags by setting the content type as html. See the link below:
https://console.bluemix.net/docs/services/personality-insights/input.html#formats

**Comment by casato** [comment]
Using jsoup libraries to clean up posts and remove HTML tags and Source code.
