### ISSUE TITLE
Measure the word count of the posts

### ISSUE THREAD

**Issue by bcdasilv** [SentimentAnalysisInSE/stackoverflow_analysis#7]
This is to understand how the posts vary in terms of length (word count) and then see if it fits to IBM guidelines. See link below:
https://console.bluemix.net/docs/services/personality-insights/input.html#sufficientGuidelines

**Comment by bcdasilv** [comment]
Plot the word count distribution if possible so we can analyze it better.

**Comment by bcdasilv** [comment]
Based on what we discussed about measuring the personality facets of individuals not posts, I don't think

**Comment by bcdasilv** [comment]
Perhaps, this is not worth exploring. Based on what we discussed about measuring the personality facets of individuals not posts, I don't think we should work on it anymore. Considering we'll work on measuring personality facets of individuals, we'll probably append several posts/comments/questions/answers of individuals (developers) in order to measure their personality facets. So, word count will not be an issue most likely. That's what I thought after our meeting.

**Comment by bcdasilv** [comment]
Perhaps, this is not worth exploring. Based on what we discussed about measuring the personality facets of individuals not posts, I don't think we should work on this specific open issue anymore. Considering we'll work on measuring personality facets of individuals, we'll probably append several posts/comments/questions/answers of individuals (developers) in order to measure their personality facets. So, word count will not be an issue most likely. That's what I thought after our meeting.

**Comment by casato** [comment]
Average is about 80 words per post. Not needed since we are appending posts from a single author together for analysis.
